functions:
  - name: 'analyse'
    handler: 'analyse.handler'
    codedir: 'var/db/baetyl/code'
  - name: 'mark'
    handler: 'mark.handler'
    codedir: 'var/db/baetyl/code'
logger:
  path: var/log/baetyl/python-service.log
  level: "debug"